# Generated by Django 5.0.6 on 2024-07-01 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
