# Generated by Django 5.0.6 on 2025-08-01 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
